version: '3.4'

services:
  traceip:
    image: traceip
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - redis
  redis:
    image: "redis:alpine"
